services:
  - type: web
    name: smartweather-ai-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HIVEMQ_HOST
        sync: false
      - key: HIVEMQ_USERNAME
        sync: false
      - key: HIVEMQ_PASSWORD
        sync: false
